server:
  port: 8080

spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: ct-main-api
      port: 27017
      host: localhost
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: create
    show-sql: true